export interface TopicManagementModel {
    topicDescriptionList: any;
    allPossibletopicDescriptionList: any;
    topicDescriptionListCount: any;
    topicDescription: any;
    contextMethodList: any;
    scriptDebug: any;
    paidServiceList: any;
    topicDesctiptionPane : any;
    topicVariables : any ;
    calculationPeriod : any;
    topicDescriptionVariable : any;
    topicPane : any;
    dataBlockList : any;
    dataBlock : any;
    dataBlockDataFieldList : any;
    dataBlockDataField : any
    dataBlockDataFieldFieldValues : any;
    dataFieldList : any;
    dataField : any;
    paneList : any;
    allPossiblePaneInTopicDescription : any;
    FIELD_SOURCE : any;
    DATA_TYPE : any;
    INPUT_TYPE : any;
    CALCULATION_EVENT : any;
    CALCULATION_TYPE : any
    CHART_TYPE : any;
    TAKEBACK_TYPE : any;
    TAKEBACK_IMAGE : any;
    TAKEBACK_ICON : any;
    ACTION_TYPE : any;
    VARIABLE_PERIOD : any;
    CONSERVATION_CATEGORY : any;
    SERIES_COLOR : any;
    SERIES_QUERY_TYPE : any;
    USER_REPORT_TYPE : any;
    USE_TYPE : any;
    fieldValueList : any;
    possibleColors : any;
    possibleStyle : any;
    fontFamilyNames : any;
    panesForSelectionAsNext : any;
    paneReportList: any;
    paneReport : any;
    paneChartList : any;
    paneChart : any;
    paneChartParameters : any;
    paneChartSeriesDefination : any;
}
