import { AllowedMenuList } from "../utility/app.allowedMenuList";

export class Users {
    public outhMeResponse: any;
    public customerResponse: any;
    public theme: string;
    public email: string;
    public phone: number;
    public id: number;
    public name: string;
    public username: string;
    public password: string;
    public role: string;
    public userId: string;
    public token: string = null;
    public userData: any;
    public socolUsername: string;
    public socolPassword: string;
    public paneNumber = 0;
    public surveyLength: number;
    public leakFocusId = 1;
    public recommendationNo: number;
    public dates: Date;
    public treadingLoadsValue: string;
    public trendId = 1;
    public profileId = 1;
    public myReportsData: {customerId : number, data : Array<any> };
    public refreshToken: string;
    public instructionHtml: string;
    public isLeakChange: boolean;
    public isSurvey: boolean;
    public isFirstTime: boolean;
    public recommendationList: any[] = [];
    public leakList: any[] = [];
    public customerMailList: any[] = [];
    public gasList: any[] = [];
    public electricityList: any[] = [];
    public electricityChargeList: any[] = [];
    public gasChargeList: any[] = [];
    public waterList: any[] = [];
    public surveyList: any[] = [];
    public trendingPartResource: any[] = [];
    public trendingProfileResource: any[] = [];
    public surveyCode: any[] = [];
    public usesList: any[] = [];
    public currentPaneNumber: any;
    public unitType = 0;
    public resourceType = 0;
    public lookupValue: string;
    public trendingProfileData: any;
    public mailContent: string;
    public mailDetail: any;
    public recommendationStatusChange: boolean;
    public types: string;
    public customerEventDetail: object;
    public addEvent: boolean;
    public allSurveyCheck: boolean;
    public electricSmartMeterList: any[] = [];
    public electricDailySmartMeterList: any[] = [];
    public gasSmartMeterList: any[] = [];
    public userEventList: any[] = [];
    public customerEventList: any[] = [];
    public searchUserList: any[] = [];
    public isDashboard: boolean;
    public lastVisitedURL : string;
    public allowedMenuList : AllowedMenuList;
    public nextSurvey : any;
}
