export interface SystemUtilityManagementModel {
    placeList: any;
    place: any;
    customerEventTypeList: any;
    custoemerEventTypeResctrictionForUserId : any;
    customerEventType: any;
    customerEventTypeCount: any;
    customerComparisonGroupList: any;
    customerComparisonGroupCount: number;
    customerComparisonGroup: any;
    customerComparisonGroupDescription: any;
    customerComparisonGroupCustomer: any;
    factorList: any;
    factor: any;
    factorCount: any;
    recalculateFactor: any;
    lookupList: any;
    lookup: any;
    lookupCount: any;
    lookupValueList: any;
    lookupValue: any;
    systemParameterList: any;
    systemParameter: any;
    systemParameterCount: any;
    logList: any;
    logCount: any;
    logs: any;
    weatherStationList: any;
    weatherStation: any;
    degreeDaysList: any;
    degreeDaysCount: any;
    degreeDays: any;
    zipCodeList: any;
    zipCode: any;
    timeZoneList: any;
    error: Error;
}
