export interface SystemManagementModel {
    customerGroupList: any;
    customerGroupCount : number;
    customerGroup: any;
    placeListByCustomerGroupId: any;
    programGroupListByCustomerGroupId: any;
    viewConfigurationList: any;
    programGroupList: any;
    programGroup: any;
    customerAlertTypeList: any;
    customerAlertTypeListCount : number;
    customerAlertType: any;
    credentialTypeList: any;
    credentialType: any;
    coachUserList: any;
    roleList: any;
    role: any;
    themesList: any;
    batchPeriod: any;
    scrapingPeriod: any;
    homeType: any;
    homeOccupancy: any;
    homeSize: any;
    comparisonCode: any;
    lotSize: any;
    calculationType: any;
    scrapingUtility: any;
    reportType: any;
    mailPeriod: any;
    contentType: any;
    debugConsoleData: any;
    error: Error;
    recommendation: any;
    recommendationList : any;
    relatedRecommendationList : any;
    relatedLeakList : any;
    selectedTopicGroupList : any;
    customerProgramGroupList : any;
}
