export interface SystemManagementModel {
    customerGroupList: any;
    customerGroup: any;
    placeListByCustomerGroupId: any;
    programGroupListByCustomerGroupId: any;
    viewConfigurationList: any;
    programGroupList: any;
    programGroup: any;
    customerAlertTypeList: any;
    customerAlertType: any;
    credentialTypeList: any;
    credentialType: any;
    coachUserList: any;
    roleList: any;
    role: any;
    themesList: any;
    batchPeriod: any;
    scrapingPeriod: any;
    homeType: any;
    homeOccupancy: any;
    homeSize: any;
    comparisonCode: any;
    lotSize: any;
    calculationType: any;
    scrapingUtility: any;
    reportType: any;
    debugConsoleData: any;
    error: Error;
}
