#!/bin/bash
set -eo pipefail

if [ $EUID -ne 0 ]; then
   echo "This command must run as root (try sudo hea ...)"
   exit 2
fi

CMD=$1
INSTANCE=$2
BRANCH=$3

if [ "$INSTANCE" = "sandbox" ]; then
   TOMCAT_USER=hea-tomcat-sb
else
   TOMCAT_USER=hea-tomcat
fi

echo "HEA-WebApp CodeDeploy: ${SUDO_USER:-$USER} is doing hea $CMD $INSTANCE" | wall -n

function stop() {
  # No Tomcat restart necessary for client-only smartAudit code
  return 0
}

function deploy() {
  SA_WEBAPP=smartAudit

  if [ "$BRANCH" = "" ]; then
     MAIN_HOME=/home/hea/projects/HEA_Main/trunk/AppServer
  else
     MAIN_HOME=/home/hea/projects/HEA_Main/branches/$BRANCH/AppServer
  fi

  echo Deploying to $TOMCAT_DIR/webapps/$SA_WEBAPP/
  rm -rf $TOMCAT_DIR/webapps/$SA_WEBAPP/*
  cp -r /home/hea/projects/HEA-WebApp/dist/* $TOMCAT_DIR/webapps/$SA_WEBAPP/
  return 0
}

function start() {
  # No Tomcat restart necessary for client-only smartAudit code
  return 0
}

function usage() {
  echo "Usage: $0 {start|stop|deploy} {sandbox|live}"
  exit 2
}


if [ "$CMD" != "update" ]; then
  if [ "$INSTANCE" = "sandbox" ]; then
    SERVICE=hea-tomcat-sandbox
    TOMCAT_DIR=/env/tomcat-sandbox
  elif [ "$INSTANCE" = "live" ]; then
    SERVICE=hea-tomcat
    TOMCAT_DIR=/env/tomcat
  else
    usage
    exit 2
  fi
fi


case "$CMD" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    deploy)
        deploy
        ;;
    *)
        usage
esac

exit $RETVAL
